language: cpp

compiler:
    - gcc

notifications:
    email:
        on_failure: always
        on_success: change

before_install:
    - sudo apt-get update
    - sudo apt-get install cmake
    - sudo pip install cpp-coveralls

install:
    - sudo apt-get install libboost1.48-all-dev zlib1g-dev

before_script:
    - wget https://github.com/samtools/htslib/archive/1.2.1.tar.gz -O /tmp/htslib-1.2.1.tar.gz
    - tar -xvf /tmp/htslib-1.2.1.tar.gz
    - cd htslib-1.2.1/ && make && sudo make install
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=coverage
    - make VERBOSE=1

script:
    - ctest -V

after_success:
    # as described at: https://github.com/eddyxu/cpp-coveralls
    - coveralls -E '.*vendor.*' -E '.*htslib.*' -E '.*build/.*' -E '/usr.*' -E '.*CMake.*' --gcov-options '\-lp' -r .. 
branches:
    only:
        - master
